#!/bin/sh
### BEGIN INIT INFO
# Provides:          tkellem
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start tkellem irc bouncer
# Description:       Enable irc bouncing goodness
### END INIT INFO

case "$1" in
  start)
    status_output=$(sudo -i -u tkellem tkellem status)
    if echo "$status_output" | grep -q "tkellem running"; then
      echo "Already started"
      echo $status_output
      exit 1
    else
      sudo -i -u tkellem tkellem start
    fi
  ;;
  stop)
    sudo -i -u tkellem tkellem stop
  ;;
  restart)
    sudo -i -u tkellem tkellem restart
  ;;
  status)
    status_output=$(sudo -i -u tkellem tkellem status)
    echo $status_output
    if echo "$status_output" | grep -q "tkellem running"; then
      exit 0
    else
      exit 1
    fi
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
  ;;
esac

exit 0
